namespace :poi do
  desc "re-create json seed files"
  task update_all: :environment do
    require 'open-uri'
    require 'nokogiri'
    require 'json'

    countries = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "East Timor",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent",
        "Samoa",
        "San Marino",
        "Sao_Tome_and_Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"]

    turkey = ["turkey"]
    poi_data = []
    results = []

    countries.each do |country|
      puts country
      url = "https://en.wikivoyage.org/wiki/#{country.gsub(" ", "_")}"
      puts url
      html_file = open(url).read
      html_doc = Nokogiri::HTML(html_file)
      html_doc.search('.listing-name a').each do |element|
        place_id = element.inner_html
        href = element.attribute('href')
        if href.to_s.include? "wiki"
          unless href.to_s.include? "#"
            url_2 = "https://en.wikivoyage.org#{href.to_s}"
            html_file_2 = open(url_2).read
            html_doc_2 = Nokogiri::HTML(html_file_2)
            description = html_doc_2.search('.mw-parser-output > p').first&.text.nil? ? '?' : html_doc_2.search('.mw-parser-output > p').first.text
            latitude = html_doc_2.search('abbr.latitude').first&.text.nil? ? '?' : html_doc_2.search('abbr.latitude').first.text
            longitude = html_doc_2.search('abbr.longitude').first&.text.nil? ? '?' : html_doc_2.search('abbr.longitude').first.text
            photo = html_doc_2.search('.wpb-banner-image').first.attributes['src'].value&.nil? ? '?' : html_doc_2.search('.wpb-banner-image').first.attributes['src'].value
            poi_info = {
              Name: element[:title],
              Description: description,
              Latitude: latitude,
              Longitude: longitude,
              Url: url_2,
              Country: country,
              Photo: photo
            }
          end
        end
      results << poi_info
      end
      File.open("#{Rails.root}/app/assets/json/country_poi_data/poi_data_#{country}.json", 'wb') do |file|
        file.write(JSON.generate(results))
      end
      results = []
    end
  end
end
end
